appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: GE/mITJpDKIoNc75c4YZjhsVrVc6H6TM4XzTn4hRwGAMBmyADVrgKJ3dsC6iNWUMc8Y5RU8E4Z5AVbFnT9dIAOFAbXg9Xyf+9khtVrVzQERQNsEvZhicVqLJn1hAm8vzRJso+M+ff/6+LRMmByG1O/sizkcAaXTxAxHs5LFVx7A3QM+0vzEi2Fjdq96OKJXphM4Otn0dl1U+hmMAZajf0q/e4ZXEwubiEME0HbxS5ATc2ApUkO+eOQuLa6yqfPbfv/6CAXsq1yea68I7GC9VXLJbkno2Kg6ddinaoPs2tLq2XHY+kQgg3v0QeBgj3Bh7v6nIlt/MTUcKwMc0exWkX5p59C+bznV06LZR7BCwwU2HDY2NSoEKX+oXbvgUG7YUG/ggf19SPSQfI9NCcEK8xycFDjB14DKs2nztkNckBD8En72AX1Ln+z+mT5ppjB0Rui6ghmD0n+IDvpJWROpXGhq8uEuDllspkk6GJAJKjwTsFyeJVweVsOmkcDwH6ntkpu83O7Ldi86pJ/dklNTWoUyMqlImuFkRZtLvyMGe+kf4P+eeDBCY09EbI8R/Rb7uyLh/VyoFhJ3F7vc5Hb4Y328NDb7ctqzhfmaEKZML29zGnAVEAYJkaoqa54OMEoxlfeiGfCCSMq8U5VQC5L58MBywS2qvGutLHLwL3gmcWEo=
