travis:
  secure:
    BINSTAR_TOKEN: dofaArHvkLm/QGtlItim57n2vNIaCSfbFmNaCsQqmBq1e4+BpbAW86Rgm3ndJLkAZR+SPrGrVzMizaRhI0EG0F7busxHfBQSoLlq7rp8/W+81tBVm2YyUjxjKRRAIm3z1PA43zhCVPI9E5F8GJXmseK8ID4Il3gxWNim5mV/eRij0mEYW1fIB+0mzz8aqG2g69jM4qWkZQoawhTQDw4OtNLzE/EhAwrrCboQV5jJu2B3q/jK/11/9t683p+6nYlEh2RR/0CujvaweDnXHhuHkwweJCtw8VT2QlkCe5SiESG2nY9Z/kmpRMlfJxzepnpbnQT7OeQuIldxuXPmZcQG2mZyStizj2JpBBIMtqH+RKKI9XKZjShwycVqh19hp0qQ0nRLgbNbepRawv+eA4X0qAAQQk0Hxe7PHsxk664U67BtDXzPeBLNW9u0mlcgl5K8JCUYLpd+CmgmJDFhJohCSI61cnSgfDmGRHsjAXSQ6Gslpm7J08mXokpjjC+v02EQANp1SWDWif2j4LycU5pS2cJk6CnbiGZ1hHEJRRUSg1cmS1q10a9HoM9gWz0SMnj8tVxfXNWk3qwq8q+IOkm6tBjaCr36fm3O6raqUk/IUrFFrujlCLWFpjAUtf+S/NEhkwfW4de9ziZGnu3YaLqLToJwMIMzxkRtBawq56B1bbw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
